# Laptop autostart additions.
exec-once = uwsm app -- hyprsunset --config ~/.config/hypr/host/hyprsunset.conf
exec-once = uwsm app -- kdeconnect-indicator
exec-once = uwsm app -- twitch-notifications
