# Laptop touchpad and pointer overrides.
input {
  sensitivity = 0.35

  touchpad {
    # Disable touchpad when typing
    disable_while_typing = true

    # Use natural (inverse) scrolling
    natural_scroll = true

    # Use two-finger clicks for right-click instead of lower-right corner
    # clickfinger_behavior = true

    # Control the speed of your scrolling
    scroll_factor = 0.4
  }
}

# Scroll speed adjustments
windowrule = match:class Alacritty, scroll_touchpad 1.50
windowrule = match:class Ghostty, scroll_touchpad 1.50
windowrule = match:class ^(Chromium|chromium|google-chrome|google-chrome-stable|google-chrome-unstable)$, scroll_touchpad 0.25
