# Laptop look overrides.
general {
    gaps_in = 0
    col.active_border = rgba(ccccccaa)
}

# Smaller floating terminal for SUPER+SHIFT+Q launcher
windowrule = size 760 500, match:class ^org\.omarchy\.terminal$
