# Extra autostart processes
exec-once = $systemBridge
exec-once = uwsm app -- twitch-notifications

# Workspace 1 layout (DP-1 portrait)
# Work hours: Slack + Discord in top area
exec-once = is-work-time && $slack
exec-once = is-work-time && $discord
# Non-work hours: second browser session in top area
exec-once = is-work-time || $browserPersonal
# Always
exec-once = [workspace 1 silent] $browserPersonal
exec-once = [workspace 1 silent] $terminal

# Workspace 2 layout (HDMI-A-2)
exec-once = [workspace 2 silent] $terminal

# Workspace 3
exec-once = is-work-time && [workspace 3 silent] $browserWork
