# Extra autostart processes
exec-once = $systemBridge
exec-once = ~/.config/hypr/bin/front-door-motion-popup
exec-once = $browserPersonal
exec-once = twitch-notifications
exec-once = solaar --window=hide

# Workspace layouts
exec-once = workspace-setup --sleep=5
