# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 2
    gaps_out = 4

    border_size = 1

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(ccccffff)
    col.inactive_border = rgba(595959aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 4

    shadow {
        enabled = true
        range = 2
        render_power = 3
        color = rgba(1a1a1aee)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = true
        size = 3
        passes = 1

        vibrancy = 0.1696
    }
}

# Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule {
  name = windowrule-1
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = w[tv1]
}

windowrule {
  name = windowrule-2
  border_size = 0
  rounding = 0
  match:float = 0
  match:workspace = f[1]
}


# Chrome opacity (patch for ~/.local/share/omarchy/default/hypr/apps/chromium.conf)
windowrule {
  name = windowrule-3
  tag = +chromium-based-browser
  match:class = (google-)?[cC]hrom(e|ium)(-stable|-unstable)?|[bB]rave-browser|Microsoft-edge|Vivaldi-stable
}

windowrule {
  name = windowrule-4
  opacity = 1 1
  match:tag = chromium-based-browser
}


# Video websites
windowrule {
  name = windowrule-5
  opacity = 1 1
  match:initial_title = .*twitch\.tv.*
}

windowrule {
  name = windowrule-6
  opacity = 1 1
  match:initial_title = .*corridordigital\.com.*
}

windowrule {
  name = windowrule-7
  opacity = 1 1
  match:initial_title = .*floatplane\.com.*
}

windowrule {
  name = windowrule-8
  opacity = 1 1
  match:initial_title = .*vivaplus\.tv.*
}

windowrule {
  name = windowrule-9
  opacity = 1 1
  match:title = .*Home Assistant.*
}


windowrule {
  name = windowrule-10
  workspace = 3
  match:class = ^(BambuStudio|OrcaSlicer)$
}

windowrule {
  name = windowrule-11
  workspace = 1
  match:class = ^(chromium)$
}

