# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale
# You must relaunch Hyprland after changing any envs (use Super+Esc, then Relaunch)

env = GDK_SCALE,1.75
env = QT_SCALE_FACTOR,1.75

monitor=DP-1,     3840x2160@143.86Hz,   -1296x0,   1.666667, transform,  1
monitor=HDMI-A-2, 3840x2160@240.00Hz,   0x504,     1.666667

workspace = 1,  name:Main Left,         monitor:DP-1,     default:true
workspace = 2,  name:Main Right A,      monitor:HDMI-A-2, default:true
workspace = 3,  name:Main Right B,      monitor:HDMI-A-2, default:false
workspace = 4,  name:Main Right C,      monitor:HDMI-A-2, default:false
workspace = 5,  name:Main Right D,      monitor:HDMI-A-2, default:false
workspace = 6,  name:Main Right E,      monitor:HDMI-A-2, default:false
